<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <OutputType>Library</OutputType>

    <!-- NuGet Package Metadata -->
    <PackageId>AsiaPayPaymentSDK</PackageId>
    <Version>1.0.1</Version>
    <Authors>Pshtiwan Hassan</Authors>
    <Description>AsiaPayPaymentSDK supporting .NET 8</Description>
    <PackageTags>asiapay, payment, sdk, .net8</PackageTags>
    <RepositoryUrl>https://github.com/pshtiwan-hassan</RepositoryUrl>
    <PackageProjectUrl>https://github.com/pshtiwan-hassan/AsiaPayPaymentSDK</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <Nullable>enable</Nullable>

    <!-- Include Readme and Icon -->
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>logo.PNG</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="logo.PNG" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.1" />
  </ItemGroup>

</Project>
